conn = nds2.connection('nds.ligo-wa.caltech.edu', 31200);
channels = {'H1:SUS-ITMX_M0_DAMP_L_IN1_DQ', ...
            'H1:SUS-ITMX_M0_DAMP_P_IN1_DQ', ...
            'H1:SUS-ITMX_M0_DAMP_Y_IN1_DQ', ...
            'H1:SUS-ITMY_M0_DAMP_L_IN1_DQ', ...
            'H1:SUS-ITMY_M0_DAMP_P_IN1_DQ', ...
            'H1:SUS-ITMY_M0_DAMP_Y_IN1_DQ', ...            '
            'H1:SUS-ETMX_M0_DAMP_L_IN1_DQ', ...
            'H1:SUS-ETMX_M0_DAMP_P_IN1_DQ', ...
            'H1:SUS-ETMX_M0_DAMP_Y_IN1_DQ', ...
            'H1:SUS-ETMY_M0_DAMP_L_IN1_DQ', ...
            'H1:SUS-ETMY_M0_DAMP_P_IN1_DQ', ...
            'H1:SUS-ETMY_M0_DAMP_Y_IN1_DQ', ...        
            'H1:SUS-OM1_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-OM1_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-OM1_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-OM2_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-OM2_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-OM2_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-OM3_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-OM3_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-OM3_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-OMC_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-OMC_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-OMC_M1_DAMP_Y_IN1_DQ', ...      
            'H1:SUS-SRM_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-SRM_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-SRM_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-SR2_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-SR2_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-SR2_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-SR3_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-SR3_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-SR3_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-BS_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-BS_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-BS_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-PRM_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-PRM_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-PRM_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-PR2_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-PR2_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-PR2_M1_DAMP_Y_IN1_DQ', ...
            'H1:SUS-PR3_M1_DAMP_L_IN1_DQ', ...
            'H1:SUS-PR3_M1_DAMP_P_IN1_DQ', ...
            'H1:SUS-PR3_M1_DAMP_Y_IN1_DQ', ...
            };
data1 = conn.fetch(1123422219, 1123422219+1500, channels);
data2 = conn.fetch(1123077617, 1123077617+1500, channels);


np = 256 * 200;
for i=1:numel(data1)
    [sp1,fr] = pwelch(double(data1(i).getData()), hanning(np), np/2, np, 256);
    [sp2,fr] = pwelch(double(data2(i).getData()), hanning(np), np/2, np, 256);
    loglog(fr, sqrt(sp1), fr, sqrt(sp2))
    title(strrep(channels{i}, '_', '\_'))
    ylim([1e-6, 1])
    xlim([1e-3, 10])
    grid
    legend('Today', 'In the past')
    pause
end
