function FontName = find_font(String,Control);

if nargin < 2
    Control = 0;
end
Fonts0 = {'SansSerif';};

%fonts with numbers, upper and lower case and special characters () etc
Fonts1 = {'Alleycat ICG';...
          'Bauhaus 93';...
          'Bonk Fatty';...
          'Bradley Hand ITC';...
          'Broadway';...
          'Brush Script MT';...
          'Burweed ICG';...
          'Calliope';...
          'Cataclysmic';
           'Catullus';...
           'Cigarstore';...
           'CrudFont';...
          'Cuckoo';...
          'Dolmen';...
          'ElderGods BB';...
           'El&Font';...
           'FairydustB';...
           'Fansilla';...
           'FantaisieArtistique';...
           'Fearth';...
           'Freebooter Italic';...
           'Freebooter Shadow';...
           'Flubber';...
           'Forte';...
           'Frosty';...
           'GeometricFog';...
           'Gigi';...
           'Gilligans Island';...
           'giraffe';...
            'Graffiti Treat';...
           'Gypsy Curse';...
           'Goombella';...
           'Harlow Solid Italic';...
          'Harrington';...
          'His Name Is Honey';...
          'Hobo';...
          'Icicle Country';...
          'Informal Roman';...
          'Isildur High';...
          'Jokerman';...
          'JudasPriest';...
          'KentuckyFriedChickenFont';...
          'Kristen ITC';...
          'LOUVAINE';...
          'Magna Carta';...
          'Magneto';...
          'Matura MT Script Capitals';...
          'Mistral';...
          'Moscoso';...
          'New Day Script';...
          'Nipple';...
          'OldeChicago';...
          'Paisley ICG 02 Alt';...
          'Pastor of Muppets';...
          'Punquin Crazy Pants';...
          'RansomThreat';...
          'Ravie';...%  'Segoe Script';...
          'Script MT Bold';...
          'Snap ITC';...
          'Viner Hand ITC';...
    };
 %fonts with numbers, one case and special characters () etc
Fonts2 = {'Amsterdam Graffiti';...
          'Bazooka';...
          'Beesknees ITC';...
          'BermudaLP-Squiggle';...
          'Boink LET';...
          'Castellar';...   'Cheap';...
          'Damn Noisy Kids';...
          'Fairly OddFont';...
          'FatStack BB';...
          'GoodGirl';...
          'Han Solo';...
          'Han Solo Pro';...
          'KR Frosted Cake';...
 };
%fonts with one case and no special characters () etc
Fonts3 = {'Calvin and Hobbes';...
         'Dark Crystal';...
         'ephesian' ;...
         'Ephesian 3D';...
         'FancyPants';...
         'Floralies';...
         'Frank';...
         'GalaxyTail';...
           'Geek a byte';...
          'Green Days';...
          'Gravity';...
           'JFRingmaster';...
          'SF Hollywood Hills Bold';...
          'Yahoo' ;...
           'vanhelsing' ;...
   };

   'intimacy';...
 
%fonts with numbers, upper and lower case and NO special characters () etc
Fonts4 = {'Dark Ages';...      
           'Purple Tentacle PD';...
          };
if Control == 0
    Fonts = Fonts0;      
elseif Control == 1
    Fonts = Fonts1;    
elseif Control == 2
    Fonts = Fonts2;
elseif Control == 3
    Fonts = Fonts3;
elseif Control == 4
    Fonts = Fonts4; 
else
    Fonts = [Fonts1;Fonts2;Fonts3;Fonts4]; 
end


FontControl = floor(1E4*sqrt(sum(String)));

numFonts = length(Fonts);
FontNumber = rem(FontControl,numFonts) + 1;
FontName = Fonts{FontNumber};
return