close all
clear all
clc

IFO         = 'H1';
Allowance   = 1e-2;

for Unit_Type=1:3
    switch Unit_Type
        case 1
            Type        = 'ISI';
                    Chambers = {'HAM2',...
                                'HAM3',...
                                'HAM4',...
                                'HAM5',...
                                'HAM6'};
        case 2
            Type        = 'ISI';
            	    Chambers = {'ITMX',...
                                'ITMY',...
                                'BS',...
                                'ETMX',...
                                'ETMY'};
            
        case 3
            Type        = 'HEPI';
            	 Chambers = {   'HAM1',...
                                'HAM2',...
                                'HAM3',...
                                'HAM4',...
                                'HAM5',...
                                'HAM6',...
                                'ITMX',...
                                'ITMY',...
                                'BS',...
                                'ETMX',...
                                'ETMY'};
    end    
    for cc = 1: length(Chambers)
    SEI_Matrices_Check (Chambers{cc},IFO,Type,Allowance)
    end
end