% [Performance Frequency_Performance] = Search_Performance(Frequency,Suppression,Display)
% This function returns the Gain margin and the phase margin of the open loop
% VL - December 20, 2012: - Initial rev: 6570

function [Performance Frequency_Max_Gain_Peaking] = Search_Performance(Frequency,Suppression,Display)

Frequency_Performance=[0.5 1 2 3 4 5 6 7 8 9 10];
for Counter_1=1:length(Frequency_Performance)
    index(Counter_1)=find(Frequency==Frequency_Performance(Counter_1));
    Performance(Counter_1)=abs(Suppression(index(Counter_1)));
end

Info_Color=[0 0.1 0.8];

switch Display
    case {1,3}
        for Counter_1=1:length(Frequency_Performance)
            cprintf(Info_Color,['Suppression of ',num2str(round(10000*Performance(Counter_1))/10000),' is obtained at ' ,num2str(round(10*Frequency_Performance(Counter_1))/10),'Hz.']); fprintf('\n');
        end
    case {2,3}
        annotation(gcf,'textbox',...
        [0.14 0.96 0.3 0.04],...
            'String',['Suppression of ',num2str(round(10000*Performance(2))/10000),' is obtained at ' ,num2str(round(10*Frequency_Performance(2))/10),'Hz.'],...
            'FontSize',14,...
            'FitBoxToText','off',...
            'LineStyle','none');
        
        annotation(gcf,'textbox',...
        [0.14 0.945 0.3 0.04],...
            'String',['Suppression of ',num2str(round(10000*Performance(4))/10000),' is obtained at ' ,num2str(round(10*Frequency_Performance(4))/10),'Hz.'],...
            'FontSize',14,...
            'FitBoxToText','off',...
            'LineStyle','none');
        
        annotation(gcf,'textbox',...
        [0.14 0.93 0.3 0.04],...
            'String',['Suppression of ',num2str(round(10000*Performance(6))/10000),' is obtained at ' ,num2str(round(10*Frequency_Performance(6))/10),'Hz.'],...
            'FontSize',14,...
            'FitBoxToText','off',...
            'LineStyle','none');
        
        annotation(gcf,'textbox',...
        [0.14 0.915 0.3 0.04],...
            'String',['Suppression of ',num2str(round(10000*Performance(8))/10000),' is obtained at ' ,num2str(round(10*Frequency_Performance(8))/10),'Hz.'],...
            'FontSize',14,...
            'FitBoxToText','off',...
            'LineStyle','none');
        
end
end
